version: '3'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    # environment:
    #   - DB_TYPE=postgresdb
    #   - DB_POSTGRESDB_HOST=postgres
    #   - DB_POSTGRESDB_PORT=5432
    #   - DB_POSTGRESDB_DATABASE=n8n
    #   - DB_POSTGRESDB_USER=n8n
    #   - DB_POSTGRESDB_PASSWORD=YOUR_PASSWORD

volumes:
  n8n_data: